// <auto-generated>
// Rewired Constants
// This list was generated on 18/09/2019 4:13:11 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
        public const int Horizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Vertical")]
        public const int Vertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Use Gadget")]
        public const int UseGadget = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Use Smokebomb")]
        public const int UseSmokebomb = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Rotate Horizontal")]
        public const int RotateHorizontal = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Rotate Vertical")]
        public const int RotateVertical = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Gadget Wheel")]
        public const int GadgetWheel = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pause")]
        public const int Pause = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Take Screenshot")]
        public const int Screenshot = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Talk To NPC")]
        public const int TalkToNPC = 19;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Horizontal")]
        public const int UIHorizontal = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Vertical")]
        public const int UIVertical = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Submit")]
        public const int UISubmit = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Cancel")]
        public const int UICancel = 16;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int UI = 1;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
}
