name: Build Project
on: [push, pull_request, workflow_dispatch]
env: 
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs: 
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - name: Checkout the repository
        id: checkout_step
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        id: cache_step
        with: 
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Build game using Unity Builder
        id: build_step
        uses: game-ci/unity-builder@v2
        env: 
          UNITY_LICENSE: ${{ secrets.UNITY_LICENCE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload Artifact
        id: upload_step
        uses: actions/upload-artifact@v2
        with: 
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: OmniFace War has finished a build with ${{job.status}}.! You can find details about the build right here - https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Send Slack Notification
        uses: keithalpichi/slack-action@0.0.6
        if: always()
        with:
          template: steps1
          steps: ${{ toJson(steps) }}
          title: Build ${{ job.status }}
          description: OmniFace War has finished a build with ${{job.status}}.

          # https://github.com + ${{ github.repository }} + /actions/runs/ + ${{ github.run_id }}

      # - name: Discord Notifcation
      #   env: 
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #   uses: Ilshidur/action-discord@master
      #   with: 
      #     args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been '

