name: Test OmniFace War
on: [push, pull_request, workflow_dispatch]
env: 
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode
    steps:
      - uses: actions/checkout@v2
        with: 
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENCE: ${{ secrets.UNITY_LICENCE }}}
        with: 
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
      - uses: actions/upload-artifact@v2
        with: 
          name: Test Results for ${{ matrix.testMode }} 
          path: ${{ steps.tests.outputs.artifactsPath }}
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: OmniFace War has finished a test run with ${{job.status}}.! You can find details about the test results right here - https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Send Slack Notification
        uses: keithalpichi/slack-action@0.0.6
        if: always()
        with:
          template: steps1
          steps: ${{ toJson(steps) }}
          title: Build ${{ job.status }}
          description: OmniFace War has finished a test run with ${{job.status}}.